version: '3.1'

services:

  wordpress:
    image: wordpress:6.2
    ports:
    - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_database
      WORDPRESS_DB_PASSWORD: F21ra2kjkjfA25f
      WORDPRESS_DB_NAME: wordpress_database
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'ALLOW_UNFILTERED_UPLOADS', true );
    volumes:
    - wordpress:/var/www/html
    - ./themes:/var/www/html/wp-content/themes/
    - ./plugins:/var/www/html/wp-content/plugins/
    - ./uploads:/var/www/html/wp-content/uploads/
    - ./languages:/var/www/html/wp-content/languages/

  db:
    image: biarms/mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress_database
      MYSQL_USER: wordpress_database
      MYSQL_PASSWORD: F21ra2kjkjfA25f
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=db
    - PMA_USER=wordpress_database
    - PMA_PASSWORD=F21ra2kjkjfA25f
    ports:
    - 8888:80
    volumes:
    - /sessions
volumes:
  wordpress: